#pragma once
// Generated by training.export_firmware — do not edit.
#define MFCC_N_FRAMES 49
#define MFCC_N_MFCC 20
#define MFCC_N_MELS 20
#define MFCC_WIN 320
#define MFCC_HOP 320
#define MFCC_NFFT 512
#define MFCC_NFFT_BINS 257
#define MFCC_PREEMPH 0.97f
#define MFCC_SR 16000
#define MFCC_FEAT_LEN 980
