"""Generate every file the firmware needs from the trained model.

Outputs:
  firmware/include/mfcc_tables.h  window / mel / highpass taps + shapes
  firmware/include/kws_model.h    the INT8 .tflite as a C array for TFLM
  models/<kw>.int8.tflite         what actually runs on the S3
  models/<kw>.float.tflite        reference for parity checks

Nothing here is hand-tuned: change shared/feature_spec.py or retrain, rerun this,
rebuild the firmware, and Python and C stay bit-comparable.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from node.capture import highpass_sos  # noqa: E402
from node.features import _FBANK, _WINDOW  # noqa: E402
from shared.config import KEYWORD, MODELS_DIR  # noqa: E402
from shared.feature_spec import FEATURE_SHAPE, FFT_BINS, SPEC  # noqa: E402

FW_INCLUDE = Path(__file__).resolve().parent.parent / "firmware" / "include"


def _c_array(name: str, arr: np.ndarray, ctype: str = "float") -> str:
    flat = np.asarray(arr, dtype=np.float32).ravel()
    body = ",\n  ".join(
        ", ".join(f"{v:.8e}" for v in flat[i : i + 8]) for i in range(0, len(flat), 8)
    )
    return f"static const {ctype} {name}[{len(flat)}] = {{\n  {body}\n}};\n"


def _highpass_defines() -> list[str]:
    """butter(2, 70 Hz) is a single biquad; ship its taps so C filters identically."""
    sos = highpass_sos()
    if sos.shape[0] != 1:
        raise SystemExit(f"expected one biquad section, got {sos.shape[0]}")
    b0, b1, b2, a0, a1, a2 = sos[0]
    if abs(a0 - 1.0) > 1e-9:
        b0, b1, b2, a1, a2 = (v / a0 for v in (b0, b1, b2, a1, a2))
    return [
        f"#define HP_CUTOFF_HZ {SPEC.highpass_hz}f",
        f"#define HP_B0 {b0:.10e}f",
        f"#define HP_B1 {b1:.10e}f",
        f"#define HP_B2 {b2:.10e}f",
        f"#define HP_A1 {a1:.10e}f",
        f"#define HP_A2 {a2:.10e}f",
    ]


def _fft_tables() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Twiddles and bit-reversal for an in-place radix-2 FFT of SPEC.n_fft points.

    Sign convention matches numpy's forward transform, exp(-2j*pi*k*n/N), so the
    C output equals numpy.fft.rfft bin for bin.
    """
    n = SPEC.n_fft
    if n & (n - 1):
        raise SystemExit(f"n_fft={n} must be a power of two for radix-2")
    t = np.arange(n // 2)
    angle = -2.0 * np.pi * t / n
    bits = int(np.log2(n))
    idx = np.arange(n, dtype=np.uint32)
    rev = np.zeros(n, dtype=np.uint16)
    for b in range(bits):
        rev |= (((idx >> b) & 1) << (bits - 1 - b)).astype(np.uint16)
    return np.cos(angle).astype(np.float32), np.sin(angle).astype(np.float32), rev


def _c_u16_array(name: str, arr: np.ndarray) -> str:
    flat = np.asarray(arr, dtype=np.uint16).ravel()
    body = ",\n  ".join(
        ", ".join(str(int(v)) for v in flat[i : i + 16]) for i in range(0, len(flat), 16)
    )
    return f"static const unsigned short {name}[{len(flat)}] = {{\n  {body}\n}};\n"


def _sparse_fbank() -> tuple[list[str], int]:
    """Mel filterbank as row-wise spans instead of a dense 40x257 matrix.

    The triangular filters are ~2% dense and none of them reaches past the bin for
    SPEC.fmax_hz, so the dense form makes the node re-read a 41 KB flash table for
    every one of the 49 frames. Storing (start, len, weights) turns 10280 MACs per
    frame into ~208 and shrinks the table small enough to stay in cache, which is
    where the bulk of the measured MFCC time was going.
    """
    starts, lens, weights = [], [], []
    for row in _FBANK:
        nz = np.nonzero(row)[0]
        if len(nz) == 0:
            starts.append(0)
            lens.append(0)
            continue
        lo, hi = int(nz[0]), int(nz[-1]) + 1
        starts.append(lo)
        lens.append(hi - lo)
        weights.extend(row[lo:hi].tolist())

    nnz = len(weights)
    max_bin = max((s + n for s, n in zip(starts, lens)), default=0)
    lines = [
        f"#define MFCC_FBANK_NNZ {nnz}",
        # Bins at or above this are never read, so the power spectrum loop stops here.
        f"#define MFCC_MAX_BIN {max_bin}",
        "",
        _c_u16_array("MFCC_FBANK_START", np.array(starts, dtype=np.uint16)),
        _c_u16_array("MFCC_FBANK_LEN", np.array(lens, dtype=np.uint16)),
        _c_array("MFCC_FBANK_W", np.array(weights, dtype=np.float32)),
    ]
    return lines, nnz


def write_mfcc_shape() -> Path:
    """Shapes only, no tables.

    kws.cpp needs the feature dimensions but not the 41 KB filterbank, and the
    tables are `static const` so every translation unit that includes them gets
    its own copy in flash.
    """
    dest = FW_INCLUDE / "mfcc_shape.h"
    dest.write_text(
        "\n".join(
            [
                "#pragma once",
                "// Generated by training.export_firmware — do not edit.",
                f"#define MFCC_N_FRAMES {SPEC.n_frames}",
                # The legacy MFCC-prefixed firmware interface now carries the
                # Log-Mel bands directly; no DCT is part of this feature recipe.
                f"#define MFCC_N_MFCC {SPEC.n_mels}",
                f"#define MFCC_N_MELS {SPEC.n_mels}",
                f"#define MFCC_WIN {int(SPEC.sample_rate * SPEC.window_ms / 1000)}",
                f"#define MFCC_HOP {int(SPEC.sample_rate * SPEC.hop_ms / 1000)}",
                f"#define MFCC_NFFT {SPEC.n_fft}",
                f"#define MFCC_NFFT_BINS {FFT_BINS}",
                f"#define MFCC_PREEMPH {SPEC.preemphasis}f",
                f"#define MFCC_SR {SPEC.sample_rate}",
                f"#define MFCC_FEAT_LEN {SPEC.n_frames * SPEC.n_mels}",
                "",
            ]
        )
    )
    print(f"wrote {dest}")
    return dest


def write_mfcc_tables() -> Path:
    write_mfcc_shape()
    dest = FW_INCLUDE / "mfcc_tables.h"
    if _FBANK.shape[1] != FFT_BINS:
        raise SystemExit(f"filterbank has {_FBANK.shape[1]} bins, spec says {FFT_BINS}")
    tw_re, tw_im, bitrev = _fft_tables()
    fbank_lines, nnz = _sparse_fbank()
    lines = [
        "#pragma once",
        "// Generated by training.export_firmware — do not edit.",
        '#include "mfcc_shape.h"',
        "",
        *_highpass_defines(),
        "",
        _c_array("MFCC_HANN", _WINDOW),
        *fbank_lines,
        _c_array("FFT_TWIDDLE_RE", tw_re),
        _c_array("FFT_TWIDDLE_IM", tw_im),
        _c_u16_array("FFT_BITREV", bitrev),
        "",
    ]
    dest.write_text("\n".join(lines))
    dense = _FBANK.size
    print(f"wrote {dest}")
    print(f"  mel filterbank: {nnz} nonzero of {dense} ({100 * nnz / dense:.1f}%)")
    return dest


def _fold_conv_bn(conv_w: np.ndarray, bn, depthwise: bool = False):
    gamma, beta, mean, var = [np.asarray(x, dtype=np.float32) for x in bn.get_weights()]
    eps = float(getattr(bn, "epsilon", 0.001))
    scale = gamma / np.sqrt(var + eps)
    if depthwise:
        w = conv_w * scale.reshape(1, 1, -1, 1)
    else:
        w = conv_w * scale.reshape(1, 1, 1, -1)
    bias = beta - mean * scale
    return w.astype(np.float32), bias.astype(np.float32)


def extract_folded(model) -> dict:
    layers = list(model.layers)
    by_type: dict[str, list] = {}
    for lyr in layers:
        by_type.setdefault(lyr.__class__.__name__, []).append(lyr)

    convs = by_type.get("Conv2D", [])
    dws = by_type.get("DepthwiseConv2D", [])
    bns = by_type.get("BatchNormalization", [])
    denses = by_type.get("Dense", [])
    if len(convs) != 5 or len(dws) != 4 or len(bns) != 9 or not denses:
        raise SystemExit(
            f"unexpected graph conv={len(convs)} dw={len(dws)} bn={len(bns)} dense={len(denses)}"
        )

    conv1_w = convs[0].get_weights()[0]
    w0, b0 = _fold_conv_bn(conv1_w, bns[0], depthwise=False)

    dw_w, dw_b, pw_w, pw_b = [], [], [], []
    bn_i = 1
    for i in range(4):
        ww, bb = _fold_conv_bn(dws[i].get_weights()[0], bns[bn_i], depthwise=True)
        dw_w.append(ww)
        dw_b.append(bb)
        bn_i += 1
        ww, bb = _fold_conv_bn(convs[i + 1].get_weights()[0], bns[bn_i], depthwise=False)
        pw_w.append(ww)
        pw_b.append(bb)
        bn_i += 1

    dense_w, dense_b = denses[0].get_weights()
    return {
        "conv1_w": w0,
        "conv1_b": b0,
        "dw_w": np.stack(dw_w),
        "dw_b": np.stack(dw_b),
        "pw_w": np.stack(pw_w),
        "pw_b": np.stack(pw_b),
        "dense_w": dense_w.astype(np.float32),
        "dense_b": dense_b.astype(np.float32),
    }


def _relu(x: np.ndarray) -> np.ndarray:
    return np.maximum(x, 0.0)


def _conv2d_same(x, w, b, stride):
    # x: H,W,Cin  w: kh,kw,Cin,Cout
    in_h, in_w, _ = x.shape
    kh, kw, _, cout = w.shape
    sh, sw = stride
    out_h = int(np.ceil(in_h / sh))
    out_w = int(np.ceil(in_w / sw))
    pad_h = max(0, (out_h - 1) * sh + kh - in_h)
    pad_w = max(0, (out_w - 1) * sw + kw - in_w)
    pt, pl = pad_h // 2, pad_w // 2
    xp = np.pad(x, ((pt, pad_h - pt), (pl, pad_w - pl), (0, 0)))
    y = np.zeros((out_h, out_w, cout), dtype=np.float32)
    for i in range(out_h):
        for j in range(out_w):
            patch = xp[i * sh : i * sh + kh, j * sw : j * sw + kw, :]
            y[i, j] = np.tensordot(patch, w, axes=([0, 1, 2], [0, 1, 2])) + b
    return y


def _dw_same(x, w, b):
    # w: kh,kw,C,1
    in_h, in_w, c = x.shape
    kh, kw, _, _ = w.shape
    out_h, out_w = in_h, in_w
    pad_h = max(0, (out_h - 1) + kh - in_h)
    pad_w = max(0, (out_w - 1) + kw - in_w)
    pt, pl = pad_h // 2, pad_w // 2
    xp = np.pad(x, ((pt, pad_h - pt), (pl, pad_w - pl), (0, 0)))
    y = np.zeros_like(x)
    for i in range(out_h):
        for j in range(out_w):
            for ch in range(c):
                patch = xp[i : i + kh, j : j + kw, ch]
                y[i, j, ch] = float(np.sum(patch * w[:, :, ch, 0])) + b[ch]
    return y


def numpy_infer(weights: dict, feats: np.ndarray) -> np.ndarray:
    x = feats.reshape(FEATURE_SHAPE).astype(np.float32)
    x = _relu(_conv2d_same(x, weights["conv1_w"], weights["conv1_b"], (2, 2)))
    for i in range(4):
        residual = x
        x = _relu(_dw_same(x, weights["dw_w"][i], weights["dw_b"][i]))
        x = _relu(_conv2d_same(x, weights["pw_w"][i], weights["pw_b"][i], (1, 1)) + residual)
    gap = x.mean(axis=(0, 1))
    logits = gap @ weights["dense_w"] + weights["dense_b"]
    e = np.exp(logits - logits.max())
    return e / e.sum()


def representative_features(keyword: str) -> np.ndarray:
    """MFCCs used to calibrate the quantiser.

    training.train saves real-mic features to models/<kw>.rep.npy. Calibrating on
    random noise instead shifts every activation scale, so we warn loudly rather
    than silently shipping a badly quantised model.
    """
    rep_path = MODELS_DIR / f"{keyword}.rep.npy"
    if rep_path.exists():
        rep = np.load(rep_path).astype(np.float32)
        print(f"calibrating INT8 on {len(rep)} dataset MFCCs from {rep_path.name}")
        return rep
    print(
        f"WARNING: {rep_path.name} missing — calibrating on synthetic noise. "
        "Rerun python -m training.train to generate a real representative set."
    )
    rng = np.random.default_rng(0)
    return rng.normal(0, 0.4, (200, *FEATURE_SHAPE)).astype(np.float32)


def write_model_header(tflite_bytes: bytes, keyword: str) -> Path:
    """The .tflite as a C array. 8-byte aligned so TFLM can read it in place."""
    dest = FW_INCLUDE / "kws_model.h"
    rows = ",\n  ".join(
        ", ".join(f"0x{b:02x}" for b in tflite_bytes[i : i + 12])
        for i in range(0, len(tflite_bytes), 12)
    )
    dest.write_text(
        "\n".join(
            [
                "#pragma once",
                "// Generated by training.export_firmware — do not edit.",
                f'#define KWS_MODEL_KEYWORD "{keyword}"',
                f"#define KWS_MODEL_LEN {len(tflite_bytes)}",
                "",
                # 16, not 8: ESP-NN's S3 kernels read weights straight out of this
                # array and only use their aligned path on a 16-byte boundary.
                f"alignas(16) static const unsigned char KWS_MODEL[{len(tflite_bytes)}] = {{",
                f"  {rows}",
                "};",
                "",
            ]
        )
    )
    print(f"wrote {dest} ({len(tflite_bytes)} model bytes)")
    return dest


def check_int8_parity(int8_bytes: bytes, x_rep: np.ndarray, float_probs: np.ndarray, keyword: str) -> None:
    """How much accuracy the quantiser costs, measured not assumed."""
    import tensorflow as tf

    interp = tf.lite.Interpreter(model_content=int8_bytes)
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    out = interp.get_output_details()[0]
    in_scale, in_zp = inp["quantization"]
    out_scale, out_zp = out["quantization"]

    n = min(len(x_rep), 200)
    q_probs = np.zeros((n, float_probs.shape[1]), dtype=np.float32)
    for i in range(n):
        q = np.round(x_rep[i : i + 1] / in_scale + in_zp).clip(-128, 127).astype(np.int8)
        interp.set_tensor(inp["index"], q)
        interp.invoke()
        q_probs[i] = (interp.get_tensor(out["index"]).astype(np.float32) - out_zp) * out_scale

    fp = float_probs[:n]
    max_dev = float(np.max(np.abs(q_probs[:, 0] - fp[:, 0])))
    mean_dev = float(np.mean(np.abs(q_probs[:, 0] - fp[:, 0])))
    agree = float((q_probs.argmax(1) == fp.argmax(1)).mean())
    print(
        f"INT8 vs float on {n} representative clips: "
        f"argmax agreement={agree * 100:.1f}%  p_keyword drift mean={mean_dev:.4f} max={max_dev:.4f}"
    )
    dest = MODELS_DIR / f"{keyword}.int8_parity.json"
    dest.write_text(
        json.dumps(
            {
                "n": n,
                "argmax_agreement": round(agree, 4),
                "p_keyword_mean_abs_drift": round(mean_dev, 5),
                "p_keyword_max_abs_drift": round(max_dev, 5),
                "calibrated_on": str(MODELS_DIR / f"{keyword}.rep.npy"),
            },
            indent=2,
        )
    )
    print(f"wrote {dest}")


def export_all(model, keyword: str = KEYWORD, verify_int8: bool = True) -> None:
    FW_INCLUDE.mkdir(parents=True, exist_ok=True)
    write_mfcc_tables()
    weights = extract_folded(model)

    # The fold has to be exact or the exported model is not the trained model.
    rng = np.random.default_rng(0)
    for tag, x in (
        ("zeros", np.zeros(FEATURE_SHAPE, dtype=np.float32)),
        ("noise", rng.normal(0, 0.4, FEATURE_SHAPE).astype(np.float32)),
    ):
        keras_p = model.predict(x[None, ...], verbose=0)[0]
        ref_p = numpy_infer(weights, x)
        err = float(np.max(np.abs(keras_p - ref_p)))
        status = "ok" if err < 1e-3 else "MISMATCH"
        print(f"fold check ({tag}) max|keras-numpy|={err:.6f} {status}")

    export_tflite_fused(weights, keyword, verify_int8=verify_int8)
    print(f"firmware export ready for keyword={keyword}")


def _frozen_infer(weights: dict):
    import tensorflow as tf

    class Frozen(tf.Module):
        @tf.function(input_signature=[tf.TensorSpec([1, *FEATURE_SHAPE], tf.float32)])
        def __call__(self, x):
            y = tf.nn.relu(
                tf.nn.bias_add(
                    tf.nn.conv2d(x, tf.constant(weights["conv1_w"]), strides=[1, 2, 2, 1], padding="SAME"),
                    tf.constant(weights["conv1_b"]),
                )
            )
            for i in range(4):
                residual = y
                y = tf.nn.relu(
                    tf.nn.bias_add(
                        tf.nn.depthwise_conv2d(
                            y, tf.constant(weights["dw_w"][i]), strides=[1, 1, 1, 1], padding="SAME"
                        ),
                        tf.constant(weights["dw_b"][i]),
                    )
                )
                y = tf.nn.relu(
                    tf.nn.bias_add(
                        tf.nn.conv2d(
                            y, tf.constant(weights["pw_w"][i]), strides=[1, 1, 1, 1], padding="SAME"
                        ),
                        tf.constant(weights["pw_b"][i]),
                    )
                    + residual
                )
            gap = tf.reduce_mean(y, axis=[1, 2])
            logits = tf.matmul(gap, tf.constant(weights["dense_w"])) + tf.constant(weights["dense_b"])
            return tf.nn.softmax(logits)

    return Frozen()


def export_tflite_fused(weights: dict, keyword: str, verify_int8: bool = True) -> None:
    import tensorflow as tf

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    frozen = _frozen_infer(weights)
    x_rep = representative_features(keyword)

    converter = tf.lite.TFLiteConverter.from_concrete_functions(
        [frozen.__call__.get_concrete_function()], frozen
    )
    float_bytes = converter.convert()
    float_path = MODELS_DIR / f"{keyword}.float.tflite"
    float_path.write_bytes(float_bytes)
    print(f"wrote {float_path} ({len(float_bytes)} bytes)")

    converter = tf.lite.TFLiteConverter.from_concrete_functions(
        [frozen.__call__.get_concrete_function()], frozen
    )
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    def _rep():
        for i in range(len(x_rep)):
            yield [x_rep[i : i + 1]]

    converter.representative_dataset = _rep
    int8_bytes = converter.convert()
    int8_path = MODELS_DIR / f"{keyword}.int8.tflite"
    int8_path.write_bytes(int8_bytes)
    ratio = len(float_bytes) / max(1, len(int8_bytes))
    print(f"wrote {int8_path} ({len(int8_bytes)} bytes, {ratio:.1f}x smaller than float)")

    if verify_int8:
        float_probs = np.stack([numpy_infer(weights, x) for x in x_rep[:200]])
        check_int8_parity(int8_bytes, x_rep, float_probs, keyword)
    write_model_header(int8_bytes, keyword)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--keyword", default=KEYWORD)
    p.add_argument("--tables-only", action="store_true")
    p.add_argument("--skip-int8-parity", action="store_true", help="skip the slow host-side INT8 comparison")
    args = p.parse_args()
    FW_INCLUDE.mkdir(parents=True, exist_ok=True)
    if args.tables_only:
        write_mfcc_tables()
        return
    keras_path = MODELS_DIR / f"{args.keyword}.keras"
    if not keras_path.exists():
        raise SystemExit(f"no {keras_path}; train first")
    from tensorflow import keras

    # Export only needs inference weights. Avoid deserialising train.py's local
    # KeywordRecall metric when this command runs in a fresh Python process.
    model = keras.models.load_model(keras_path, compile=False)
    export_all(model, args.keyword, verify_int8=not args.skip_int8_parity)


if __name__ == "__main__":
    main()
